meta_product_name: "What's For Dinner"
meta_title: "What's For Dinner - I'll have what they're having!"
meta_description: "What's For Dinner is the app allowing foodies to get inspired by what their network is cooking."
meta_image: "cover.png"
